### ISSUE TITLE
Not detecting music playing on Brave (Windows x64) browser

### ISSUE THREAD

**Issue by HyperLemons** [tekkeon/YTM-Plus#36]
Not sure why, disabling shields (Brave's built in adblocker that's based on uBlock Origin) doesn't fix it either.

**Comment by mkossoris** [comment]
Hey there, thanks for the report! I just noticed this on my end on Chrome as well. I believe YouTube Music updated one of their element selectors which is causing the break. Looking into getting a fix out shortly.

**Comment by mkossoris** [comment]
Just submitted a fix to the Chrome web store. Usually they review and publish it within a day or two. Will keep this ticket open until we can confirm it's fixed.

**Comment by mkossoris** [comment]
Chrome just notified me that they've published the update. I just tested it, and everything seems to be working properly 👍

**Comment by HyperLemons** [comment]
Thanks for fixing so quickly!
